import { writeFileSync } from "node:fs"
import { resolve } from "node:path"
import twemoji from "twemoji"
import { languageOptions } from "../src/lib/config.js"
import { SVG_BASE } from "../src/lib/twemoji-svg.js"

const entries: Array<[string, string]> = []

for (const lang of languageOptions) {
  const cp = twemoji.convert.toCodePoint(lang.icon)
  const url = `${SVG_BASE}${cp}.svg`
  const res = await fetch(url)
  if (!res.ok) {
    console.error(`Failed to fetch ${url}: ${res.status}`)
    process.exit(1)
  }
  const svg = await res.text()
  entries.push([cp, svg])
}

const lines = [
  "// Auto-generated by scripts/generate-twemoji-svgs.ts — DO NOT EDIT",
  "",
  `export const FLAG_SVGS: Record<string, string> = {`,
  ...entries.map(
    ([cp, svg]) => `  ${JSON.stringify(cp)}: ${JSON.stringify(svg)},`
  ),
  "}",
  "",
]

const outPath = resolve(import.meta.dirname, "../src/lib/twemoji-flag-svgs.ts")
writeFileSync(outPath, lines.join("\n") + "\n")
console.log(`twemoji SVGs generated (${entries.length} flags)`)
