/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/_index'
import { Route as IndexIndexRouteImport } from './routes/_index.index'
import { Route as IndexSlugRouteImport } from './routes/_index.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexIndexRoute = IndexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)
const IndexSlugRoute = IndexSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndexRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexIndexRoute
  '/$slug': typeof IndexSlugRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof IndexSlugRoute
  '/': typeof IndexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_index': typeof IndexRouteWithChildren
  '/_index/$slug': typeof IndexSlugRoute
  '/_index/': typeof IndexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/$slug' | '/'
  id: '__root__' | '/_index' | '/_index/$slug' | '/_index/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_index/': {
      id: '/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexIndexRouteImport
      parentRoute: typeof IndexRoute
    }
    '/_index/$slug': {
      id: '/_index/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof IndexSlugRouteImport
      parentRoute: typeof IndexRoute
    }
  }
}

interface IndexRouteChildren {
  IndexSlugRoute: typeof IndexSlugRoute
  IndexIndexRoute: typeof IndexIndexRoute
}

const IndexRouteChildren: IndexRouteChildren = {
  IndexSlugRoute: IndexSlugRoute,
  IndexIndexRoute: IndexIndexRoute,
}

const IndexRouteWithChildren = IndexRoute._addFileChildren(IndexRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
